Repository Submitty/Submitty, pull requests merged in 2019-07, with the labels that each got.

#3982 [ Bugfix: Autograding] Fix Improper Variable Name in Autograding Router
  grading/python/submitty_router.py
Labels: bug

#3517 Add Confetti to Submitty
  site/app/templates/autograding/AutoResults.twig
  site/app/templates/autograding/TAResults.twig
  site/app/templates/submission/homework/CurrentVersionResults.twig
  site/app/views/submission/HomeworkView.php
  site/public/css/server.css
  site/public/js/confetti.js
Labels: URGENT, enhancement / feature request, question / design / discussion needed

#4018 [Bugfix] Fix Travis CI Python lint error
  .travis.yml
Labels: URGENT

#4013 Fix Badge title and confetti on Autograding only gradeables
  site/app/templates/autograding/AutoResults.twig
  site/app/templates/autograding/TAResults.twig
  site/app/views/AutoGradingView.php
Labels: URGENT

#4025 [Bugfix:Autograding] Automatically Copy And Validate Executables
  grading/load_config_json.cpp
Labels: bug

#4114 [Bugfix:InstructorUI] Added date picker to late days page
  site/app/controllers/admin/LateController.php
  site/app/templates/admin/LateDays.twig
Labels: Instructor UI
