Repository Submitty/Submitty, pull requests merged in 2021-06, with the labels that each got.

#6516 [UI/UX:InstructorUI] Collection of Contrast Fixes
  site/public/css/bootstrap.css
  site/public/css/colors.css
  site/public/css/officeHoursQueue.css
  site/public/css/server.css
Labels: URGENT / PRIORITY

#6411 [UI/UX:InstructorUI] Off-Center Error Banner
  site/public/css/electronic.css
Labels: Instructor UI, bug

#6424 [Bugfix:TAGrading] Peer grading ta and student notes shown
  site/app/templates/grading/electronic/GradingPanelHeader.twig
  site/app/templates/grading/electronic/RubricPanel.twig
  site/app/views/grading/ElectronicGraderView.php
  site/public/js/gradeable.js
  site/public/js/ta-grading-rubric.js
Labels: TA Grading, bug

#6576 [Testing:Developer] Speed up integration test
  tests/integrationTests/build_main_configure.sh
  tests/integrationTests/compile_configure_bin.sh
  tests/integrationTests/lib.py
Labels: Testing / Continuous Integration (CI)

#6648 [Bugfix:TAGrading] Fix Viewing Other Comments
  site/public/js/ta-grading-rubric.js
Labels: URGENT / PRIORITY
