Repository Submitty/Submitty, pull requests merged in 2023-08, with the labels that each got.

#9521 [Bugfix:Submission] Notebook Zip Download No User Responses
  site/app/controllers/MiscController.php
  site/app/libraries/Access.php
  site/app/models/gradeable/Gradeable.php
Labels: security

#9517 [Feature:Developer] Integrate Cypress Cloud
  .github/workflows/submitty_ci.yml
  site/cypress.config.ts
  site/cypress/e2e/cypress-feature/accessibility.spec.js
  site/cypress/e2e/cypress-feature/auth_token.spec.js
  site/cypress/e2e/cypress-feature/bulkupload.spec.js
  site/cypress/e2e/cypress-feature/courseMaterials.spec.js
  site/cypress/e2e/cypress-feature/docker_ui.spec.js
  site/cypress/e2e/cypress-feature/gradeables/gradeable.spec.js
  site/cypress/e2e/cypress-feature/gradeables/gradeable_results.spec.js
  site/cypress/e2e/cypress-feature/grading_interface/files_panel.spec.js
  site/cypress/e2e/cypress-feature/grading_interface/student_info_panel.spec.js
  site/cypress/e2e/cypress-feature/grading_stats.spec.js
  site/cypress/e2e/cypress-feature/late_days_allowed.spec.js
  site/cypress/e2e/cypress-feature/manageSessions.spec.js
  site/cypress/e2e/cypress-feature/navigation_page.spec.js
  site/cypress/e2e/cypress-feature/pdfs.spec.js
  site/cypress/e2e/cypress-feature/polls.spec.js
  site/cypress/e2e/cypress-feature/profile.spec.js
  site/cypress/e2e/cypress-feature/pronouns_change.spec.js
  site/cypress/e2e/cypress-feature/sidebar.spec.js
  site/cypress/e2e/cypress-feature/simple_grading.spec.js
  site/cypress/e2e/cypress-feature/test_forum.spec.js
  site/cypress/e2e/cypress-feature/url_flexibility.spec.js
  site/cypress/e2e/cypress-system/autograding_status_1.spec.js
  site/cypress/e2e/cypress-system/autograding_status_2.spec.js
  site/cypress/e2e/cypress-system/login.spec.js
Labels: Testing / Continuous Integration (CI)

#9079 [UI/UX:System] localization/language translation
  .github/workflows/db_check.yml
  .setup/CONFIGURE_SUBMITTY.py
  .setup/bin/update_repos.sh
  .setup/bin/versions.sh
  .setup/distro_setup/ubuntu/20.04/setup_distro.sh
  .setup/distro_setup/ubuntu/22.04/setup_distro.sh
  .setup/install_submitty/install_site.sh
  .setup/install_system.sh
  .setup/testing/setup.sh
  migration/migrator/migrations/system/20230609162569_php_intl.py
  sbin/load_lang.php
  site/app/libraries/Core.php
  site/app/libraries/Output.php
  site/app/models/Config.php
  site/app/models/Locale.php
  site/app/templates/GlobalHeader.twig
  site/app/templates/UserProfile.twig
  site/app/views/GlobalView.php
  site/tests/LocalizeTest.php
  site/tests/app/models/ConfigTester.php
Labels: Localization

#9415 [UI/UX:System] User Preferred Locale Selection
  migration/migrator/data/course_tables.sql
  migration/migrator/data/submitty_db.sql
  migration/migrator/migrations/course/20230610140032_user_locale.py
  migration/migrator/migrations/master/20230809163220_user_locale.py
  migration/migrator/triggers/master/sync_courses_user.sql
  migration/migrator/triggers/master/sync_user.sql
  site/app/controllers/UserProfileController.php
  site/app/libraries/Core.php
  site/app/libraries/database/DatabaseQueries.php
  site/app/models/Config.php
  site/app/models/User.php
  site/app/templates/UserProfile.twig
  site/app/views/UserProfileView.php
  site/public/css/user-profile.css
  site/public/js/user-profile.js
  site/tests/app/models/ConfigTester.php
Labels: Localization

#9658 [Feature:Calendar] Calendar Color Select + Legend
  site/app/models/CalendarInfo.php
  site/app/templates/admin/Docker.twig
  site/app/templates/calendar/Calendar.twig
  site/app/templates/calendar/CalendarOptions.twig
  site/app/views/calendar/CalendarView.php
  site/public/css/calendar.css
  site/public/css/colors.css
  site/public/js/calendar.js
Labels: calendar

#9693 [SECURITY][Bugfix:System] Prevent caching the resource
  site/public/index.php
Labels: security

#9695 [SECURITY][Bugfix:System] Prevents embedding of pages
  site/public/index.php
Labels: security

#9694 [SECURITY][Bugfix:System] Prevent Content-Sniffing Attacks
  site/public/index.php
Labels: security

#9728 [Bugfix:System] Files in iframe Grading Interface
  site/public/index.php
Labels: URGENT / PRIORITY
