Repository Submitty/Submitty, pull requests merged in 2024-11, with the labels that each got.

#10889 [Feature:Developer] Add santa duck
  site/app/controllers/GlobalController.php
  site/public/img/moorthy_duck/santa_duck.svg
Labels: Abandoned PR - Needs New Owner

#10922 [Documentation:Autograding] Add Rust "Hello World" example.
  .setup/data/courses/development.yml
  more_autograding_examples/rust_hello_world/config/config.json
  more_autograding_examples/rust_hello_world/submissions/correct.rs
  more_autograding_examples/rust_hello_world/submissions/incorrect.rs
Labels: Abandoned PR - Needs New Owner

#11102 [Documentation:Autograding] Prolog Sample Config
  .setup/data/courses/development.yml
  more_autograding_examples/prolog_simple_goal/config/config.json
  more_autograding_examples/prolog_simple_goal/config/test_input/knowledge_base.prolog
  more_autograding_examples/prolog_simple_goal/submissions/correct.pl
  more_autograding_examples/prolog_simple_goal/submissions/incorrect.pl
Labels: Autograding, Docker Container Autograding

#11035 [UI/UX:RainbowGrades] Redirect reports to customization
  site/app/controllers/GlobalController.php
  site/app/templates/admin/RainbowCustomization.twig
  site/cypress/e2e/Cypress-UI/sidebar.spec.js
Labels: Rainbow Grades, Instructor UI

#10888 [Feature:Developer] Add tree_duck
  site/app/controllers/GlobalController.php
  site/public/img/moorthy_duck/tree_duck.svg
Labels: Abandoned PR - Needs New Owner

#11149 [Bugfix:Submission] Fix Duplicate Keys on Late Day Cache
  site/app/libraries/database/DatabaseQueries.php
Labels: TA Grading / TA UI, late days / extensions, URGENT / PRIORITY

#10873 [Refactor:RainbowGrades] clear Customization baseline
  site/app/models/RainbowCustomization.php
  site/phpstan-baseline.neon
Labels: Rainbow Grades, refactor / coding style
