Repository Submitty/Submitty, pull requests merged in 2025-05, with the labels that each got.

#11329 [Feature:InstructorUI] Notification for self registration
  migration/migrator/data/course_tables.sql
  migration/migrator/migrations/course/20250113084243_registration_email.py
  site/app/controllers/NotificationController.php
  site/app/controllers/course/CourseRegistrationController.php
  site/app/libraries/database/DatabaseQueries.php
  site/app/models/User.php
  site/app/templates/NotificationSettings.twig
  site/app/views/NotificationView.php
  site/cypress/e2e/Cypress-Feature/registration.spec.js
  site/tests/app/models/UserTester.php
Labels: good first review

#11141 [Testing:InstructorUI] Add tests for deleting gradeables
  site/app/models/gradeable/Gradeable.php
  site/app/templates/navigation/DeleteGradeableForm.twig
  site/cypress/e2e/Cypress-Gradeable/deletion.spec.js
Labels: Abandoned PR - Needs New Owner

#11606 [Refactor:InstructorUI] Replace toggle columns with vue
  site/app/templates/Vue.twig
  site/app/templates/admin/users/StudentList.twig
  site/app/templates/admin/users/ToggleManageStudentsColumns.twig
  site/app/views/admin/UsersView.php
  site/cypress/e2e/Cypress-UI/pronouns_change.spec.js
  site/package-lock.json
  site/package.json
  site/public/css/server.css
  site/public/js/manage-students.js
  site/vue/src/components/popup.vue
  site/vue/src/components/toggleColumns.vue
Labels: refactor / coding style, Instructor UI

#11417 [Bugfix:Developer] Add missing answer to notebook itempool
  more_autograding_examples/notebook_itempool/config/test_output/math_4_answer.txt
  more_autograding_examples/notebook_itempool_random/config/test_output/math_4_answer.txt
Labels: Abandoned PR - Needs New Owner

#11602 [Bugfix:InstructorUI] Fix peer grading panel
  site/app/controllers/MiscController.php
  site/app/controllers/grading/ElectronicGraderController.php
  site/app/libraries/Access.php
  site/app/models/gradeable/Gradeable.php
  site/app/views/grading/ElectronicGraderView.php
Labels: Peer Grading, Instructor UI, Abandoned PR - Needs New Owner

#11470 [Bugfix:CourseMaterials] Add Course Material Path Length Limit
  site/app/controllers/course/CourseMaterialsController.php
Labels: Abandoned PR - Needs New Owner

#11023 [Feature:TAGrading] Add text option for checkpoint lab
  .setup/bin/sample_courses/models/gradeable.py
  site/app/controllers/admin/AdminGradeableController.php
  site/app/controllers/grading/SimpleGraderController.php
  site/app/templates/admin/admin_gradeable/rubric/CheckpointsRubric.twig
  site/app/templates/admin/admin_gradeable/rubric/NumericRubric.twig
  site/app/templates/grading/simple/Display.twig
  site/public/css/admin-gradeable.css
  site/public/js/simple-grading.js
Labels: Abandoned PR - Needs New Owner

#11637 [Bugfix:InstructorUI] Fixed Email Status Button Alignment
  site/public/css/email-status.css
Labels: bug, Instructor UI

#9445 [Refactor:Autograding] Dockerize existing autograding examples
  .setup/CONFIGURE_SUBMITTY.py
  .setup/install_system.sh
  more_autograding_examples/c_failure_messages/config/config.json
  more_autograding_examples/c_malloc_not_allowed/config/config.json
  more_autograding_examples/choice_of_language/config/config.json
  more_autograding_examples/comment_count/config/config.json
  more_autograding_examples/cpp_buggy_custom/config/config.json
  more_autograding_examples/cpp_cats/config/config.json
  more_autograding_examples/cpp_count_ts/config/config.json
  more_autograding_examples/cpp_custom/config/config.json
  more_autograding_examples/cpp_hidden_tests/config/config.json
  more_autograding_examples/cpp_provided_code/config/config.json
  more_autograding_examples/cpp_random_input_output/config/config.json
  more_autograding_examples/cpp_simple_lab/config/config.json
  more_autograding_examples/docker_choice_of_language/config/config.json
  more_autograding_examples/early_submission_incentive/config/config.json
  more_autograding_examples/file_check/config/config.json
  more_autograding_examples/image_diff_mirror/config/config.json
  more_autograding_examples/input_output_subdirectories/config/config.json
  more_autograding_examples/leaderboard/config/config.json
  more_autograding_examples/minimal_code_editing/config/config.json
  more_autograding_examples/multiple_pdf_annotations/config/config.json
  more_autograding_examples/notebook_basic/config/config.json
  more_autograding_examples/notebook_expected_string/config/config.json
  more_autograding_examples/notebook_filesubmission/config/config.json
  more_autograding_examples/notebook_itempool/config/config.json
  more_autograding_examples/notebook_itempool_random/config/config.json
  more_autograding_examples/notebook_time_limit/config/config.json
  more_autograding_examples/pdf_exam/config/config.json
  more_autograding_examples/pdf_word_count/config/config.json
  more_autograding_examples/pre_commands/config/config.json
  more_autograding_examples/python_custom_docker_rlimits/config/config.json
  more_autograding_examples/python_custom_validation/config/config.json
  more_autograding_examples/python_linehighlight/config/config.json
  more_autograding_examples/python_multipart_static_analysis/config/config.json
  more_autograding_examples/python_random_input_output/config/config.json
  more_autograding_examples/python_simple_homework/config/config.json
  more_autograding_examples/test_notes_upload/config/config.json
  more_autograding_examples/test_notes_upload_3page/config/config.json
  more_autograding_examples/tolerance_check/config/config.json
  more_autograding_examples/vcs_submissions/config/config.json
  site/cypress/e2e/Cypress-UI/docker_ui.spec.js
  tests/integrationTests/tests/choice_of_language/__init__.py
Labels: Abandoned PR - Needs New Owner
