Repository Submitty/Submitty, pull requests merged in 2025-07, with the labels that each got.

#11854 [Bugfix:System] Fix install_site Script for Vagrant VMs
  .setup/INSTALL_SUBMITTY_HELPER.sh
  .setup/INSTALL_SUBMITTY_HELPER_BIN.sh
  .setup/INSTALL_SUBMITTY_HELPER_SITE.sh
  .setup/install_submitty/install_site.sh
Labels: bug, URGENT / PRIORITY

#11869 [Refactor:Developer] Consistent Vue File Naming
  site/app/templates/GlobalHeader.twig
  site/app/templates/admin/users/StudentList.twig
  site/app/templates/grading/electronic/Details.twig
  site/app/views/admin/SqlToolboxView.php
  site/vue/src/components/PerformanceWarning.vue
  site/vue/src/components/Popup.vue
  site/vue/src/components/ToggleColumns.vue
  site/vue/src/components/sql_toolbox/DisplayQueryResults.vue
  site/vue/src/components/sql_toolbox/DownloadQuery.vue
  site/vue/src/components/sql_toolbox/ManageSqlQuery.vue
  site/vue/src/components/sql_toolbox/RunQuery.vue
  site/vue/src/components/sql_toolbox/SaveSqlQuery.vue
  site/vue/src/components/sql_toolbox/SqlSchema.vue
  site/vue/src/pages/SqlToolboxPage.vue
Labels: refactor / coding style

#11870 [Bugfix:InstructorUI] Fixed Config Selector Refresh
  site/app/templates/admin/admin_gradeable/AdminGradeableAuto.twig
  site/public/js/admin-gradeable-updates.js
Labels: bug, URGENT / PRIORITY

#11860 [Feature:InstructorUI] Add/Delete Files in Gradeable Editor
  site/app/controllers/admin/AdminGradeableController.php
  site/app/templates/admin/admin_gradeable/AdminGradeableAuto.twig
  site/public/css/admin-gradeable.css
  site/public/js/admin-gradeable-updates.js
Labels: Instructor UI

#10677 [Feature:InstructorUI] Team Grade Override
  site/app/controllers/admin/GradeOverrideController.php
  site/app/libraries/database/DatabaseQueries.php
  site/app/templates/admin/GradeOverride.twig
  site/cypress/e2e/Cypress-Feature/grade_override.spec.js
  site/phpstan-baseline.neon
  site/public/js/server.js
  site/vue/src/components/OverrideTeamPopup.vue
Labels: late days / extensions, Instructor UI
