Repository Submitty/Submitty, pull requests merged in 2025-01, with the labels that each got.

#8845 [Feature:InstructorUI] Add ability to delete docker imgs in UI
  .setup/data/system_docker_containers.json
  migration/migrator/data/submitty_db.sql
  migration/migrator/migrations/master/20240219141515_docker_image.py
  sbin/shipper_utils/update_and_install_workers.py
  site/app/controllers/DockerInterfaceController.php
  site/app/libraries/database/DatabaseQueries.php
  site/app/templates/admin/Docker.twig
  site/app/views/admin/DockerView.php
  site/cypress/e2e/Cypress-UI/docker_ui.spec.js
  site/phpstan-baseline.neon
  site/public/js/docker_interface.js
  site/tests/app/controllers/DockerInterfaceControllerTester.php
Labels: Abandoned PR - Needs New Owner

#11343 [Bugfix:InstructorUI] Correctly set allowed minutes on config
  bin/set_allowed_mins.py
Labels: bug, URGENT / PRIORITY, Instructor UI, good first review

#11270 [Bugfix:TAGrading] Checkpoint validation when max is 0
  site/public/js/simple-grading.js
Labels: good first review

#11341 [Bugfix:RainbowGrades] Remove alert when section label blank
  site/app/models/RainbowCustomizationJSON.php
  site/public/js/rainbow-customization.js
Labels: Rainbow Grades, good first review
