Repository Submitty/Submitty, pull requests merged in 2025-06, with the labels that each got.

#11640 [UI/UX:Submission] Improve Duplicate Submission Handling
  site/app/templates/submission/homework/SubmitBox.twig
  site/app/views/submission/HomeworkView.php
  site/public/css/submitbox.css
  site/public/js/drag-and-drop.js
  site/public/js/submit-box.js
Labels: Submission / Team Submission, Student UI

#11483 [Feature:RainbowGrades] Add omit sections from statistics
  site/app/controllers/admin/ReportController.php
  site/app/models/RainbowCustomization.php
  site/app/models/RainbowCustomizationJSON.php
  site/app/templates/admin/RainbowCustomization.twig
  site/public/css/rainbow-customization.css
  site/public/js/rainbow-customization.js
Labels: Abandoned PR - Needs New Owner

#11792 [Feature:InstructorUI] Filter Withdrawn Students in Gradeables
  site/app/controllers/grading/ElectronicGraderController.php
  site/app/templates/grading/electronic/Details.twig
  site/app/templates/grading/simple/Display.twig
  site/app/views/grading/ElectronicGraderView.php
  site/cypress/e2e/Cypress-Feature/files_panel.spec.js
  site/cypress/e2e/Cypress-TAGrading/ta_grading_details.spec.js
  site/cypress/e2e/Cypress-UI/pdfs.spec.js
  site/cypress/e2e/Cypress-UI/student_info_panel.spec.js
  site/public/css/details.css
  site/public/js/details.js
  site/public/js/simple-grading.js
Labels: Instructor UI
