Repository Submitty/Submitty, pull requests merged in 2025-09, with the labels that each got.

#12062 [Bugfix:InstructorUI] Fix Simple Gradeable Key
  site/app/templates/grading/simple/Display.twig
  site/public/css/details.css
  site/public/css/server.css
  site/public/css/simple-grading.css
Labels: Instructor UI, good first review

#12063 [Bugfix:InstructorUI] Fix Rubric Rendering on Firefox
  site/public/js/gradeable.js
Labels: URGENT / PRIORITY

#12069 [Feature:Notifications] Removed Late Days in Title
  sbin/send_notification.py
Labels: Notifications / Email

#12075 [Bugfix:InstructorUI] Simple Gradeable Checkpoint Fix
  site/app/templates/grading/simple/Display.twig
  site/public/css/simple-grading.css
Labels: URGENT / PRIORITY, Instructor UI
