Repository Submitty/Submitty, pull requests merged in 2025-02, with the labels that each got.

#11326 [Feature:RainbowGrades] Assign buckets if empty
  site/app/models/RainbowCustomization.php
  site/public/js/rainbow-customization.js
Labels: Rainbow Grades

#11359 [Refactor:System] Set empty preferred names to NULL
  migration/migrator/data/submitty_db.sql
  migration/migrator/migrations/master/20250121144600_make_empty_preferred_names_null.py
  site/app/models/User.php
  site/app/views/UserProfileView.php
  site/phpstan-baseline.neon
Labels: Database / SQL Toolbox

#11328 [Bugfix:TAGrading] fix alert on disabled button
  site/app/templates/Navigation.twig
  site/app/views/NavigationView.php
  site/cypress/e2e/Cypress-UI/navigation_page.spec.js
Labels: good first review

#11388 [Refactor:Forum] Mark post unread with Doctrine
  site/app/controllers/forum/ForumController.php
  site/app/entities/forum/ThreadAccess.php
Labels: good first review

#11259 [Bugfix:TAGrading] Simple Gradeable CSV Upload
  site/app/controllers/grading/SimpleGraderController.php
  site/phpstan-baseline.neon
  site/public/js/simple-grading.js
Labels: good first review

#11438 [Bugfix:InstructorUI] Fix error in superuser email status page
  site/app/entities/email/EmailEntity.php
Labels: good first review

#11184 [UI/UX:Forum] Improved Colors for Deleted Posts
  site/public/css/colors.css
  site/public/css/forum.css
Labels: Discussion Forum, good first review
